apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-pvc-d8f4fb19-e56e-4749-93dd-ec4aa50ab9c1.yaml
  - pvc-dv-fedora-demo-2-pink-raven-11.yaml
  - pv-pvc-d0866613-2d7e-48f9-8231-473c94246979.yaml
  - pvc-fedora-demo-2.yaml
  - vm-fedora-demo-2.yaml
