apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.17.27
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: fedora
    kubevirt.io/created-by: 6ff41784-23d4-47f9-a11f-1f839df4e11f
  name: fedora-demo-2
  namespace: demo-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '32212254720'
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-d0866613-2d7e-48f9-8231-473c94246979
