apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.17.27
  name: dv-fedora-demo-2-pink-raven-11
  namespace: demo-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '1073741824'
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-d8f4fb19-e56e-4749-93dd-ec4aa50ab9c1
