apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-pvc-5a091ede-0451-4b6e-b4db-020c78ae1572.yaml
  - pvc-fedora-azure-salamander-94.yaml
  - vm-fedora-azure-salamander-94.yaml
