apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: openshift-storage
  name: pvc-9ee997d8-b3a0-4cf3-92a5-740c4e5551f2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: openshift-storage
    driver: openshift-storage.rbd.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: openshift-storage
    volumeAttributes:
      clusterID: openshift-storage
      imageFeatures: layering,deep-flatten,exclusive-lock,object-map,fast-diff
      imageFormat: '2'
      imageName: csi-vol-5ac8dd3e-4b0d-4233-a19f-7ae09eb08888
      journalPool: ocs-storagecluster-cephblockpool-replica2
      mapOptions: krbd:rxbounce
      mounter: rbd
      pool: ocs-storagecluster-cephblockpool-replica2
      storage.kubernetes.io/csiProvisionerIdentity: 1742498047845-2521-openshift-storage.rbd.csi.ceph.com
    volumeHandle: 0001-0011-openshift-storage-000000000000000d-5ac8dd3e-4b0d-4233-a19f-7ae09eb08888
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ocs-storagecluster-ceph-rbd-replica2
  volumeMode: Block
