apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph
  name: pvc-d4122ca2-29e6-4763-acfe-3ca4efe7cb9d
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-2822bae1-674e-4eb6-90cb-0ab75b9a8adb
      journalPool: cephblockpool
      pool: cephblockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1768580981037-5315-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-2822bae1-674e-4eb6-90cb-0ab75b9a8adb
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-ceph-block
  volumeMode: Block
