apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.20.3
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: fedora
    kubevirt.io/created-by: 2e4158a0-c0a4-49c6-a651-27107552298c
  name: fedora-blush-felidae-19
  namespace: koray
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '32212254720'
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-d4122ca2-29e6-4763-acfe-3ca4efe7cb9d
