apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph
  name: pvc-b327a328-30e8-49a4-89e1-5beaeaadbfa4
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-4b1970ae-ea3f-435c-9b86-102fb933c750
      journalPool: cephblockpool
      pool: cephblockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1760080938830-5071-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-4b1970ae-ea3f-435c-9b86-102fb933c750
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Block
