apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: openshift-storage
  name: pvc-99e796f8-3c13-4856-b4d4-b3c68aa1a393
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: openshift-storage
    driver: openshift-storage.rbd.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: openshift-storage
    volumeAttributes:
      clusterID: openshift-storage
      imageFeatures: layering,deep-flatten,exclusive-lock,object-map,fast-diff
      imageFormat: '2'
      imageName: csi-vol-cf0dcf1e-14f7-48fb-beb6-32420b754f8a
      journalPool: ocs-storagecluster-cephblockpool
      mapOptions: krbd:rxbounce
      mounter: rbd
      pool: ocs-storagecluster-cephblockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1757542522237-9281-openshift-storage.rbd.csi.ceph.com
    volumeHandle: 0001-0011-openshift-storage-0000000000000001-cf0dcf1e-14f7-48fb-beb6-32420b754f8a
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
