apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-pvc-91cff9e1-5e40-4a34-95dd-3acb71d9dd1e.yaml
  - pvc-fedora-amaranth-flamingo-32.yaml
  - vm-fedora-amaranth-flamingo-32.yaml
