apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
    volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph
  name: pvc-5926960b-5559-49d6-bd74-9ef972f23b6b
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-f35854c6-52c4-4e1e-8c3c-fd7302b9e4fd
      journalPool: cephblockpool
      pool: cephblockpool
      storage.kubernetes.io/csiProvisionerIdentity: 1760080938830-5071-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-f35854c6-52c4-4e1e-8c3c-fd7302b9e4fd
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Block
