apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.17.27
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: fedora
    kubevirt.io/created-by: 24bb1972-28b6-46e1-9497-20d2329f5310
  name: fedora-amaranth-flamingo-32
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '32212254720'
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-91cff9e1-5e40-4a34-95dd-3acb71d9dd1e
