apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.17.27
    kubevirt.io/created-by: 24bb1972-28b6-46e1-9497-20d2329f5310
  name: dv-fedora-amaranth-flamingo-32-apricot-chameleon-22
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '1073741824'
  storageClassName: rook-ceph-block
  volumeMode: Block
  volumeName: pvc-5926960b-5559-49d6-bd74-9ef972f23b6b
